### ISSUE TITLE
[idea] Parking column not affected by moveonduedate

### ISSUE THREAD

**Issue by hpiedcoq** [dmorlitz/kanboard-TaskMoveOnDueDate#2]
Hi!
According to you, could it be possible to make this plugin work on every column *except* a parking column.
Use-case : in my board, when the due-date is passed, the note goes in an alert column. The crontab checks it every day at 8:00am.
In this board, there is a column that says :"ok, it's not done but I'm working on it", which means that the procedure is ongoing. So notes in thin column shouldn't be affected any more by the moveonduedate.

Dunno if I'm clear.

**Comment by dmorlitz** [comment]
Let me make sure I understand correctly.  You have a board with columns A, B, C, D and E (for example)
1) D is your overdue column
2) E is your “OK - I know it’s overdue but still keep it active”

You want overdue items in column A, B and C to move to D when they are overdue but not from column E to D, correct?

I believe I could update the plugin to be aware of the source column.  The downside would be that you would need to make an automatic action for A—>D, B—>D and C—>D.  I am not aware how to make a condition that says (not E)—>D.  If I were to do this then I would probably make it a separate plugin so this one could still pay attention to all columns.

Let me ask you another question. Would it be sufficient to move your alerted items to column E and then push the due date out so it is no longer overdue?  I have a different plugin which puts buttons on each card to easily extend the due date without having to go directly into the task.  You can configure up to 3 intervals to push out cards, so you might have +7, +30 and +60 and the due date would be updated.  Finally, I have a 3rd plugin which will set the due date automatically when you move a card to a specific column.  So you could set an automatic action that adds a select number of days when cards are moved into column E.

Would either of those solutions work?  Or would you prefer to leave the date alone?  I think that making the 2nd plugin would only take a few lines of code and I could probably do it early next week.

**Comment by hpiedcoq** [comment]
Wow, you're so fast answering! thank you! 

> You want overdue items in column A, B and C to move to D when they are overdue but not from column E to D, correct?

Correct!

> I believe I could update the plugin to be aware of the source column. The downside would be that you would need to make an automatic action for A—>D, B—>D and C—>D. I am not aware how to make a condition that says (not E)—>D. If I were to do this then I would probably make it a separate plugin so this one could still pay attention to all columns.

Way too complicated. Forget about it. The ratio benefit/time to code is clearly to bad.

>I have a different plugin which puts buttons on each card to easily extend the due date without having to go directly into the task. You can configure up to 3 intervals to push out cards, so you might have +7, +30 and +60 and the due date would be updated.

That's a real smart solution, I think as my maximum delay would be around +30.
I'll give a try to kanboard-CardPushDate that seems to perfectly fit my need.

Thank you for the fantastic work you're doing with these addons! It's just amazing.

**Comment by dmorlitz** [comment]
I hope the CardPushDate plugin works for you. Just FYI, you can set up to 3 push intervals. Setting a value of 0 disables one of the intervals from appearing. There are also a few other buttons you can make appear to make your life easier like close task, add comment and move task.

The settings for this plugin are set in the configure board area. This way you can have different intervals per board. The settings are honored on search views and the dashboard.

There is no way to set global values so you would need to set the intervals you want per board
